#
# Morning
#
- alias: Get dressed
  trigger:
    platform: time
    at: '07:30:00'

  condition:
    condition: state
    entity_id: group.all_devices
    state: home

  action:
    service: light.turn_on
    entity_id: light.kids_bedroom_2
    data:
      brightness: 77

#
# Afternoon
#
- alias: Sunset
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 5.0
  action:
    service: scene.turn_on
    entity_id: scene.sunset
