#
# Morning
#
- alias: Get dressed
  trigger:
    platform: time
    at: '07:30:00'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'group.all_devices'
        state: 'home'
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'

  action:
    service: light.turn_on
    entity_id: light.kids_bedroom_ceiling
    data:
      brightness: 77

#
# Afternoon
#
- alias: Sunset
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 2.5

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: home
      - condition: time
        before: '19:30:00'

  action:
    service: scene.turn_on
    entity_id: scene.sunset

#
#
#
- alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.ios_andrea
    data:
      message: 'Update for Home Assistant is available.'
