default_view:
  view: yes
  icon: mdi:home 
  entities:
    - group.bedroom
    - group.kids_bedroom
    - group.climate
    - group.scenes
    - group.automation
    - group.alarm_clock

#
# Master bedroom
#
bedroom:
  name: Bedroom
  icon: mdi:human-male-female
  entities:
    - light.andrea
    - light.marta
    - group.bedroom_ceiling

bedroom_ceiling:
  name: Bedroom ceiling
  icon: mdi:spotlight
  entities:
    - light.bedroom_near_marta
    - light.bedroom_near_andrea
    - light.bedroom_near_window
    - light.bedroom_near_closet

#
# Kids bedroom
#
kids_bedroom:
  name: Kids Bedroom
  icon: mdi:human-child
  entities:
    - group.kids_bedroom_ceiling

kids_bedroom_ceiling:
  name: Kids bedroom ceiling
  icon: mdi:spotlight
  entities:
    - light.kids_near_closet
    - light.kids_near_window
    - light.kids_near_davide
    - light.kids_near_door

#
# Climate
#
climate:
  name: Climate
  entities:
    - climate.hallway
    - sensor.hallway_thermostat_humidity
    - sensor.yr_symbol
    - sun.sun

climate_view:
  name: Climate
  view: yes
  icon: mdi:weather-sunny
  entities:
    - climate.hallway
    - sensor.yr_symbol
    - sun.sun
    - sensor.hallway_thermostat_humidity
    - sensor.hallway_thermostat_hvac_state
    - sensor.hallway_thermostat_operation_mode
    - sensor.hallway_thermostat_target
    - sensor.hallway_thermostat_temperature
    - binary_sensor.hallway_thermostat_fan
    - binary_sensor.hallway_thermostat_has_leaf
    - binary_sensor.hallway_thermostat_is_locked
    - binary_sensor.hallway_thermostat_is_using_emergency_heat
    - binary_sensor.hallway_thermostat_online

#
# Scenes
#
scenes:
  name: Scenes
  entities:
    - scene.sunrise
    - scene.wakeup
    - scene.sunset

#
# Automation
#
automation:
  name: Automation
  entities:
    - automation.sunrise
    - automation.wakeup
    - automation.get_dressed
    - automation.sunset

#
# Alarm clock
#
alarm_clock:
  name: Morning Alarm & Wakeup
  entities:
    - input_boolean.alarm_clock
    - input_select.wake_up_time

#
# Devices
#
devices:
  name: Devices
  view: yes
  icon: mdi:cellphone-link
  entities:
    - group.devices_view

devices_view:
  name: Devices
  entities:
    - group.all_devices
    - device_tracker.andrea_5f5bc153966f47ef8ebc147bf40d76a2
    - sensor.andrea_battery_level
    - sensor.andrea_battery_state
    - device_tracker.marta_2f6f9326c3df4948aefa4059e7471cfd
    - sensor.martas_iphone_battery_level
    - sensor.martas_iphone_battery_state
    - sensor.andreas_ipad_battery_level
    - sensor.andreas_ipad_battery_state
