mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True

automation:
  alias: 'Turn off lights when leaving home'

  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'

    # If given, will trigger when state has been the to state for X time.
    for:
      minutes: 5

  action:
    service: light.turn_off
    entity_id: group.all_lights
